version: '2'

services:
  mysql:
    image: mysql
    container_name: GC-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./mysql:/var/lib/mysql