App\Domain\Entity\Lap:
  type: entity
  table: laps
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    truckId:
      type: uuid
    startTime:
      type: datetime_immutable
    pickupIds:
      type: array
    status:
      type: string
    garbageWeight:
      type: float
      nullable: true
    unloadTime:
      type: datetime_immutable
      nullable: true
    district:
      type: integer
      nullable: true
    garbageType:
      type: string
      nullable: true
