App\Domain\Entity\Bucket:
  type: entity
  table: buckets
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    rfid:
      type: string
    garbageType:
      type: string
    pickUpDays:
      type: array

  embedded:
    position:
      class: Position
