App\Domain\Entity\Event:
  type: entity
  table: events
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    time:
      type: datetime_immutable
      nullable: true
    data:
      type: text
