App\Domain\Entity\GarbagePickup:
  type: entity
  table: pickups
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    bucketId:
      type: uuid
    collectionTime:
      type: datetime_immutable
    garbageType:
      type: string
