App\Domain\Entity\Complainment:
  type: entity
  table: complainments
  id:
    id:
      type: uuid
      generator: { strategy: NONE }
  fields:
    complainmentCloseTime:
      type: datetime_immutable
      nullable: true
    complainmentProcessingStartTime:
      type: datetime_immutable
      nullable: true
    complainmentSubmitTime:
      type: datetime_immutable
    complainmentType:
      type: string
    confirmationMessage:
      type: string
      nullable: true
    description:
      type: string
    rejectionMessage:
      type: string
      nullable: true
    status:
      type: string
    submitter:
      type: string

  embedded:
    position:
      class: Position
